# parents = [...]

device = 'cuda'
num_workers = 0

[saving]
	name = 'test'

	saveroot = '../trained_nets'
	tblog = true
	logdate = true

	track_best = true

#   save_freq = -1

[viz]
	stats_decay = 0.01
#   print_freq = -1
#	criterion_args = ['pred', 'y']

[training]
	seed = 0
	epochs = 20
	start = 0

	batch_size = 128

#[evaluation]

[dataset]
	dataroot = '../local_data'

	shuffle = true
	drop_last = false

[model]

#	type = mlp
#	latent_dim = 16
#   fc = [64, 64]

	nonlin = 'prelu'

	upsampling = 'bilinear'
	downsampling = 'max'

	norm_type = 'instance'


[optim]
	type = 'adam'
	lr = 1e-3
	weight_decay = 0
	momentum = 0
	beta1 = 0.9
#	beta2 = 0.999

#	lr_decay = {type='factor', epochs=10, factor=0.1}





