

_meta.script_name: train

#parents: [cmd]

#resume: test-pycharm_200707-021212
#
#override:
#  eval:
#    identifier: test
#    overwrite: True
#    use_testset: True

#extend: 5000

parents: [demo]

#checkpoint.freq: 2

#model.net.factors: 1

#model:
#  spec_norm: True

#  down: stride

#  down: None
#  norm: batch
#  nonlin: mish

#  net:
#    strides: 2
#    factors: 1

name: test-pycharm

inline: True

#dataset.name: mnist

#output.save_freq: 800



