
_meta.script_name: train

parents: [demo]


#resume: test-pycharm_201226-211608


#epochs: 2
budget: 2000
#checkpoint.freq: 2

name: test-pycharm

inline: True

#model.optim.lr:
#  _type: scheduler/cos
#  value: 0.01
#  end: 0.0001
#  freq: 100
#  skew: 0.5
#  limit: <>budget
#  include_zero: False


