
_meta.script_name: eval

parents: [scheduler, conv, basics]



#epochs: 5
budget: 100
#budget: 100
#records.freq: 1
#model.optim.lr.freq: 1

name: test-pycharm

inline: True

#model.optim.lr.end: 0.01
#model.optim.lr.kurtosis: 0.5
#model.optim.lr.skew: 0.7



