
_meta.script_name: train

#  script_name: eval

#resume: test-pycharm_200707-021212
#
#override:
#  eval:
#    identifier: test
#    overwrite: True
#    use_testset: True

#extend: 5000

parents: ['demo']



name: 'test-pycharm'

#inline: True

dataset.name: mnist

#output.save_freq: 800



