parents: ['origin']

run:
  _type: run
  _mod: ['cls-run', 'timed-run']

name: 'test-cmd'

output:
    save_freq: -1

    tensorboard: True

dataset:
    name: 'mnist'

    download: False
    labeled: True

    batch_size: 128

    val_split: 0.166666

training:
    epochs: 10

model:
    _type: 'simple'

    nonlin: 'elu'

    norm: None

    net:
        _type: 'conv'

        channels: [32, 32, 32, 32]
        strides: 1

        fc_hidden: [64, 32]

        in_shape: '<>din'
        latent_dim: '<>dout'

    optim_type: 'adam'
    lr: 1.e-3
    weight_decay: 1.e-4
#    momentum: 0.9

#    scheduler_type: step
#    scheduler_step: 2
#    scheduler_decay: 0.4


