parents: ['origin']

run._type: run

name: 'test-mnist'

records:
  _type: records
  freq: 100

validation:
  _type: run/epoch
  freq: 10000

checkpoint:
  _type: run/checkpoint
  freq: 10000


dataset:
  name: 'mnist'

  download: False
  labeled: True

  batch_size: 128

  split.val: 0.1666666


training:
  epochs: 10


model:
  _type: model
  _model_type: simple

  nonlin: elu

  norm: None

  net:
    _type: multilayer

#    pool: max

    nonlin: elu

    layer_type: conv-layer
    channels: 32
    down: 2

    layers:
      - _type: <>layer_type
      - _type: <>layer_type
      - _type: <>layer_type
      - _type: <>layer_type

    last:
      _type: mlp
      hidden: [64, 32]


  optim_type: 'adam'
  lr: 1.e-3
  weight_decay: 1.e-4
#  momentum: 0.9
#
#  scheduler_type: step
#  scheduler_step: 2
#  scheduler_decay: 0.4


