parents: ['origin']

#inline: True

name: test-mnist

epochs: 10

validation.freq: 1000
checkpoint.freq: 1000
print.freq: 100


records.freq: 100


dataset:
  name: mnist

  download: False
  labeled: True

  batch_size: 128

  split.val: 0.1666666

  device: cpu


model:
  _model_type: simple

  nonlin: elu

  norm: None

  net:
    _type: multilayer

#    pool: max

    nonlin: elu

    layer_type: conv-layer
    channels: 32
    down: 2

    layers:
      - _type: <>layer_type
      - _type: <>layer_type
      - _type: <>layer_type
      - _type: <>layer_type

    last:
      _type: mlp
      hidden: [64, 32]

  optim:
    _type: adam
    lr: 1.e-3
    weight_decay: 1.e-4

