# parents = [...]

step_device: <>device
device: cuda
num_workers: 0
seed: 0

run:
  _type: run
  _mod.inline: 5
  allow-missing-mods: True


clock._type: clock


validation._type: run/epoch
checkpoint._type: run/checkpoint
print._type: run/print

logger:
  _type: logger
  tensorboard: true
  log_dir: <>path

stats:
  _type: stats-manager
  reset-modes: [val, test]
  stat-collection-fmts:
    train: "{}/train"
    val: "{}/val"
    test: "{}/test"


records:
  _type: records
  include-zero: True


dataset:
  _type: dataset

  batch_size: 128

  shuffle: true
  drop_last: false

  store_keys: ['din', 'dout']

model:
  _type: model


