# parents = [...]

step_device: <>device
device: cuda
num_workers: 0
seed: 0

#limit: <>budget

run:
  _type: run
  _mod:
    inline: 5
  allow-missing-mods: True


clock:
  _type: clock
  tau: 1

validation:
  _type: run/epoch
  loader-seed: <>seed
checkpoint._type: run/checkpoint
viz._type: run/viz
print._type: run/print

logger:
  _type: logger
  tensorboard: true
  log_dir: <>path

  use_log_fmts: True

stats:
  _type: stats-manager
  reset-modes: [val, test]


records:
  _type: records
  include-zero: True


dataset:
  _type: dataset

  batch_size: 128

  shuffle: true
  drop_last: false

  store_keys: ['din', 'dout']

model:
  _type: model


