
# Saving
save-root:          results/
#name: test-ppo # specify in command
save-freq:          10

#seed:               10

# Logging
log-date:           True
log-tb:             False
log-txt:            False

# Task
env:                InvertedPendulum-v2

budget-steps:       1000000
steps-per-itr:      2048
device:             cpu

# Agent
agent:              ppoclip
discount:           0.99
clip:               0.2

#norm-adv:           True

# Policy
policy:             normal
model:              norm-mlp
hidden:             [8,8]
nonlin:             prelu

# Baseline
baseline:           norm-mlp
b-hidden:           [8,8]
b-nonlin:           prelu

b-scale-max:        True

b-optim-type:       adam
b-lr:               3e-4
b-weight-decay:     1e-4

b-epochs:           10
b-batch-size:       64

# Optimization
epochs:             10
batch-size:         64
optim-type:         adam
lr:                 3e-4
weight-decay:       0




