alg:                npg

policy:             gaussian
model:              mlp
hidden:             [5]

baseline:           lin
#b-hidden:           [5]
#b-lr:               1e-2
#b-optim-type:       sgd
#b-nesterov:         True
#b-epochs:           10
#b-batch-size:       128
b-time-order:       3
b-obs-order:        3

env:                pendulum

save-root:          results/
seed:               100

num-gen-workers:    4
num-eval-workers:   4

num-iter:           100
num-traj:           20
save-freq:          10
num-eval:           10
#viz:                2

step-size:          0.01

