policy:             cat
hidden:             [5]

time-order:         3
obs-order:          3

env:                cartpole

save-root:          results/
seed:               100

num-iter:           100
num-traj:           20
save-freq:          10
num-eval:           10

delta:              0.001
gamma:              0.99

reg-coeff:          1e-10
max-steps:          10
nonlinearity:       elu


