alg:                vpg

policy:             gaussian
model:              mlp
hidden:             [5]

baseline:           lin
#b-hidden:           [5]
#b-lr:               1e-2
#b-optim-type:       sgd
#b-nesterov:         True
#b-epochs:           10
#b-batch-size:       128
b-time-order:       3
b-obs-order:        3

env:                pendulum

save-root:          results/
seed:               100

num-iter:           100
num-traj:           20
save-freq:          50
num-eval:           10

nonlinearity:       elu
optim-type:         rmsprop
lr:                 1e-3
weight-decay:       1e-4