
saveroot: trained_nets/
name: test-mnist
logdate: True

print-freq: -1

no-unique-tests: True
seed: 1
no-test: True
use-val: True
val-per: 0.025
test-per: 0.1
epochs: 50
decay-epochs: 12
decay-factor: 0.5
batch-size: 128
num-workers: 4

optim-type: adam
lr: 1e-3
weight-decay: 1e-4
momentum: 0.9

dataset: mnist

model-type: auto
nonlin: elu
latent-dim: 2
fc: [32]

channels: [16, 24, 32]
kernels: [3, 3, 3]
factors: [2, 3, 3]
downsampling: max
upsampling: deconv
batch-norm: True

beta: 1

loss-type: bce
loss-scale: 1

