
saveroot: trained_nets/
name: test-catcher-ae
logdate: True

dataset: hf-seq
data: [/home/fleeb/workspace/pose_nets/se3nets-pytorch/data/catcher-mass1/]

print-freq: -1

no-unique-tests: True
seed: 1
no-test: True
use-val: True
val-per: 0.1
test-per: 0.01
epochs: 50
decay-epochs: 15
decay-factor: 0.2
batch-size: 128
num-workers: 8

optim-type: rmsprop
lr: 1e-3
weight-decay: 1e-4
momentum: 0.9

din: [3, 120, 180]

model-type: auto
nonlin: prelu
latent-dim: 32
fc: [128, 64]

channels: [8, 16, 32, 64, 128]
kernels: [5, 3, 3, 3, 3]
factors: [2, 3, 3, 2, 2]
downsampling: max
upsampling: bilinear
batch-norm: True

beta: 1

loss-type: bce
loss-scale: 1

