

data: [/home/fleeb/workspace/ml_datasets/audio/yt/processed/]

save-root: trained_nets/
name:       test-naive-3000-final

batch-size:  128
train-per:  0.75
val-per:    0.1
split-path: /home/fleeb/workspace/ml_datasets/audio/yt/split.pth.tar

num-workers: 4
dataset: yt
data-mode: genre

model:        naive
data-type:    spec
sample-rate:  44100
step-len:     1
seq-len:      3000
hop:          1000
#use-batch-norm: True

dense-labeling: False
use-fc: True

model-hop:    50
model-ws:     50
model-n:      256

mel-hop:      10
mel-ws:       50
mel-n:        150

rec-dim:    256
rec-num-layers: 3
rec-type:   gru
fc-dims:    [256]

epochs:     25
seed:       100


loss-scale:   1

optimization: adam #rmsprop
lr:           1e-3
weight-decay: 1e-4
momentum:     0.9
decay-epochs: 12

disp-freq:    10
log-date:     True
tblog:        True
#no-test:      True
