

data: [/home/fleeb/workspace/ml_datasets/audio/yt/processed/]

save-root: trained_nets/
name:       test

batch-size:  128
train-per:  0.75
val-per:    0.1
split-path: /home/fleeb/workspace/ml_datasets/audio/yt/split.pth.tar

num-workers: 2
dataset: yt
data-mode: genre

model:        arc
data-type:    wav
sample-rate:  44100
step-len:     1
seq-len:      5000
hop:          1000
#use-batch-norm: True

#dense-labeling: True

model-hop:    40
model-ws:     50
model-n:      512

latent-dim: 512
rec-loss:   mse
dense-labeling: True
use-fc: True

rec-loss-wt: 1
cls-loss-wt: 1
var-loss-wt: 1

rec-dim:    512
rec-num-layers: 2
rec-type:   gru
fc-dims:    [256]

epochs:     20
seed:       100

loss-scale:   1

optimization: adam #rmsprop
lr:           1e-3
weight-decay: 1e-4
momentum:     0.9
decay-epochs: 16

disp-freq:    10
log-date:     True
tblog:        True
no-test:      True
